# /opt/apps/afya/docker-compose.yml

version: "3.8"

services:
    afya_app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: afya-app
        restart: always
        volumes:
            - .:/var/www
        networks:
            - web

    afya_db:
        image: mysql:8.0
        container_name: afya-db
        restart: always
        environment:
            MYSQL_DATABASE: afya
            MYSQL_ROOT_PASSWORD: Kishmee@mg5
            MYSQL_USER: afya
            MYSQL_PASSWORD: Kishmee@mg5
        volumes:
            - afya-db-data:/var/lib/mysql
        networks:
            - web

volumes:
    afya-db-data:

networks:
    web:
        external:
            name: zahra_default
