version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: laravel-filament-app
        container_name: afya-app
        restart: unless-stopped
        volumes:
            - ./:/var/www
        environment:
            SERVICE_NAME: app
            SERVICE_TAGS: local
        depends_on:
            - db

    web:
        image: nginx:alpine
        container_name: laravel_web
        restart: unless-stopped
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./:/var/www
            - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
            - /etc/letsencrypt:/etc/letsencrypt:ro
        depends_on:
            - app

    portal:
        build:
            context: ./portal
            dockerfile: Dockerfile
        image: nextjs-portal
        container_name: portal-app
        restart: unless-stopped
        environment:
            NODE_ENV: production
            PORT: 3001
            NEXT_PUBLIC_API_URL: https://romuz.com.ly
        expose:
            - "3001"
        depends_on:
            - app
        healthcheck:
            test: [ "CMD", "wget", "-qO-", "http://localhost:3001/" ]
            interval: 30s
            timeout: 5s
            retries: 5

    db:
        image: mysql:8.0
        container_name: afya_db
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: Kishmee@mg5
            MYSQL_DATABASE: afya
            MYSQL_USER: afya_user
            MYSQL_PASSWORD: Kishmee@mg5
        volumes:
            - db_data:/var/lib/mysql

volumes:
    db_data:
