version: "3.8"

services:
    # Laravel + Filament application (PHP-FPM)
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: afya-app
        restart: always
        volumes:
            - .:/var/www:delegated
        networks:
            - proxy-net
        healthcheck:
            test: [ "CMD", "php", "-r", "exit(extension_loaded('pdo_mysql') ? 0 : 1);" ]
            interval: 30s
            timeout: 10s
            retries: 3

    # MySQL database
    db:
        image: mysql:8.0
        container_name: afya-db
        restart: always
        environment:
            MYSQL_DATABASE: afya
            MYSQL_ROOT_PASSWORD: Kishmee@mg5
            MYSQL_USER: afya
            MYSQL_PASSWORD: Kishmee@mg5
        volumes:
            - afya-db-data:/var/lib/mysql
        networks:
            - proxy-net
        healthcheck:
            test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
            interval: 10s
            timeout: 5s
            retries: 5

volumes:
    afya-db-data:

networks:
    proxy-net:
        external: true
